import Link from "next/link";
import {ArrowRight,Camera,BrainCircuit,CheckCircle2,Car,Clock3,CreditCard,History,ScanLine,ShieldCheck,BadgeCheck,ReceiptText,Navigation2,BellRing,ExternalLink} from "lucide-react";
import {PhoneMockup,ResultCard} from "@/components/site";

const evidence=["Parking signs","Road markings","Kerb & bay context","Time restrictions","Paid parking","Permit rules","EV restrictions"];

export default function Home(){return <>
<section className="hero"><div className="hero-orbit orbit-a"/><div className="hero-orbit orbit-b"/><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow">AI-assisted UK parking guidance</span><h1 className="h1">Parking rules,<br/><span className="blue-text">made simple.</span></h1><p className="lead">Scan a UK parking sign or road markings. NaviParka reads the visible rules, explains the important restrictions in plain English and helps you handle payment or timing when needed.</p><div className="actions"><Link href="/download" className="btn btn-primary btn-lg">Get NaviParka <ArrowRight size={17}/></Link><Link href="/how-it-works" className="btn btn-secondary btn-lg">See how it works</Link></div><div className="trust-strip"><span><CheckCircle2 size={15}/> Android first</span><span><ShieldCheck size={15}/> Safety-conscious AI</span><span><Navigation2 size={15}/> Built for UK parking</span></div></div><div className="hero-device"><PhoneMockup kind="scanner"/><div className="floating-proof proof-one"><ScanLine size={16}/><span><b>Evidence detected</b><small>Sign or road markings</small></span></div><div className="floating-proof proof-two"><CheckCircle2 size={16}/><span><b>Rules simplified</b><small>Important conditions surfaced</small></span></div></div></div></section>

<section className="section section-tight"><div className="container"><div className="section-heading centered"><span className="eyebrow">The NaviParka flow</span><h2 className="h2">Scan. Understand. Take the next step.</h2><p className="lead">Built around the few minutes when you need to understand a parking restriction quickly.</p></div><div className="flow-grid"><div className="flow-card"><div className="flow-top"><span>01</span><Camera size={24}/></div><h3>Scan</h3><p>Point the camera at a parking sign or road markings—no scan-type toggle required.</p></div><div className="flow-arrow">→</div><div className="flow-card"><div className="flow-top"><span>02</span><BrainCircuit size={24}/></div><h3>Understand</h3><p>NaviParka reads the visible rules and turns the important conditions into plain English.</p></div><div className="flow-arrow">→</div><div className="flow-card"><div className="flow-top"><span>03</span><CheckCircle2 size={24}/></div><h3>Act</h3><p>See payment details, open the payment service or keep track of a time limit.</p></div></div></div></section>

<section className="section"><div className="container grid2 product-split"><div className="visual-panel"><PhoneMockup kind="scanner" label="MOCKUP-SCANNER"/></div><div className="product-copy"><span className="eyebrow">AI Parking Scanner</span><h2 className="h2">Point your camera. NaviParka identifies the parking evidence.</h2><p className="lead">The current scanner is designed around parking signs and road markings. You do not need to tell NaviParka what you are scanning first—it analyses what is visible in the frame.</p><div className="pillrow">{evidence.map(x=><span className="pill" key={x}>{x}</span>)}</div><Link href="/parking-scanner" className="text-link roomy">Explore the scanner <ArrowRight size={15}/></Link></div></div></section>

<section className="section decision-section"><div className="container"><div className="section-heading"><span className="eyebrow">Clear parking guidance</span><h2 className="h2">The rules, without the parking-sign puzzle.</h2><p className="lead">NaviParka surfaces the important restriction first, then the details that affect what you should do next.</p></div><div className="grid3 result-grid"><ResultCard type="good" title="You can park here"><div className="status-row"><span>Allowed until</span><b>6:00 PM</b></div><div className="status-row"><span>Maximum stay</span><b>2 hours</b></div></ResultCard><ResultCard type="warn" title="Payment required"><div className="status-row"><span>Provider</span><b>Shown in app</b></div><div className="status-row"><span>Location code</span><b>Ready to copy</b></div></ResultCard><ResultCard type="bad" title="Don't park here"><div className="status-row"><span>Restriction</span><b>Permit holders</b></div><div className="status-row"><span>Applies</span><b>8 AM–6 PM</b></div></ResultCard></div></div></section>

<section className="section"><div className="container"><div className="utility-grid"><div className="utility-card payment-card"><div className="utility-copy"><span className="utility-icon"><ReceiptText size={21}/></span><span className="eyebrow">Payment handoff</span><h3>Go from reading the sign to paying online.</h3><p>When NaviParka identifies supported payment information, it can show the payment service and location code, then give you a direct action to open the relevant external payment service.</p></div><div className="payment-ui"><div className="payment-head"><CreditCard size={20}/><b>Pay before you walk away</b></div><div className="status-row"><span>Payment service</span><b>Provider identified</b></div><div className="status-row"><span>Location code</span><b>686995</b></div><button className="screen-action">Open payment service <ExternalLink size={14}/></button></div></div><div className="utility-stack"><div className="mini-feature"><Clock3 size={22}/><div><h3>Smart parking timer.</h3><p>Track an active time-limited session and keep the end time close at hand.</p></div><div className="timer-sample"><strong>00:51</strong><small>remaining</small></div></div><div className="mini-feature"><BellRing size={22}/><div><h3>Move-car reminders.</h3><p>Turn reminders on so NaviParka can alert you before the parking time runs out.</p></div><div className="history-sample"><span>Parking session <b className="good-text">Active</b></span><span>Reminder <b>On</b></span></div></div></div></div></div></section>

<section className="section"><div className="container grid2 product-split reverse-mobile"><div className="product-copy"><span className="eyebrow">Driver context</span><h2 className="h2">Your vehicle and Blue Badge settings stay part of the decision.</h2><p className="lead">Add the vehicle you use for parking and enable Blue Badge mode when relevant. NaviParka can use that context when presenting new scan guidance.</p><div className="context-list"><div><Car size={19}/><span><b>Add your vehicle</b><small>Keep relevant vehicle information available to new scans.</small></span></div><div><BadgeCheck size={19}/><span><b>Blue Badge mode</b><small>Apply Blue Badge context to new scans when enabled.</small></span></div></div><Link href="/vehicle-awareness" className="text-link roomy">See driver context <ArrowRight size={15}/></Link></div><div className="visual-panel"><PhoneMockup kind="vehicle" label="MOCKUP-PROFILE"/></div></div></section>

<section className="section"><div className="container"><div className="utility-grid"><div className="mini-feature"><History size={22}/><div><span className="eyebrow">Scan history</span><h3>Revisit previous parking checks.</h3><p>Keep scan history enabled to return to earlier signs and results from your profile.</p></div><div className="history-sample"><span>Victoria Road <b>Recent</b></span><span>Tennyson Road <b>Previous</b></span></div></div><div className="mini-feature"><ShieldCheck size={22}/><div><span className="eyebrow">Account controls</span><h3>Privacy and account settings in one place.</h3><p>Manage scan-history preferences, view privacy information, sign out or delete your account.</p></div></div></div></div></section>

<section className="section"><div className="container"><div className="trust-band"><div className="trust-copy"><span className="eyebrow">Built for real-world decisions</span><h2 className="h2">Helpful AI.<br/>Clear limitations.</h2><p className="lead">NaviParka helps interpret visible parking evidence, but temporary notices, obscured signs and conditions outside the camera frame can still matter.</p><Link href="/safety" className="btn btn-secondary">Read about safety <ArrowRight size={16}/></Link></div><div className="trust-cards">{[["Evidence-first",ScanLine,"Starts with the sign or road markings you scan."],["Clear conditions",CheckCircle2,"Times, payment and restrictions are surfaced in readable language."],["Driver context",Car,"Vehicle and Blue Badge settings can add relevant context."],["Driver responsibility",ShieldCheck,"Always check the physical signage and local conditions before leaving your vehicle."]].map(([t,I,d]:any)=><div className="trust-card" key={t}><span><I size={20}/></span><b>{t}</b><p>{d}</p></div>)}</div></div></div></section>

<section className="section"><div className="container"><div className="band"><span className="eyebrow">Roadmap · Version 2</span><h2 className="h2">Live parking map is coming next.</h2><p className="lead">The current NaviParka release does not include a parking map or directions. Those discovery features are being kept separate from the features available today.</p><Link href="/parking-map" className="text-link roomy">View roadmap note <ArrowRight size={15}/></Link></div></div></section>

<section className="section final-section"><div className="container"><div className="final-cta"><div className="final-copy"><span className="eyebrow">NaviParka for Android</span><h2 className="h2">Read the rules.<br/>Handle the next step.</h2><p className="lead">Scan parking evidence, understand restrictions and get the payment or timing information you need before you walk away.</p><Link href="/download" className="btn btn-primary btn-lg">Get NaviParka <ArrowRight size={16}/></Link><small>AI-assisted guidance. Always check local signage and conditions.</small></div><div className="final-device"><PhoneMockup kind="result" label="MOCKUP-FINAL-APP"/></div></div></div></section>
</>}
