import Link from "next/link";
import {ArrowRight,Camera,BrainCircuit,CheckCircle2,Car,Clock3,CreditCard,History,Map,ScanLine,ShieldCheck,BatteryCharging,MapPinned,ReceiptText,Navigation2} from "lucide-react";
import {MapMockup,PhoneMockup,ResultCard} from "@/components/site";

const evidence=["Parking signs","Road markings","Kerb markings","Parking bays","Time restrictions","Paid parking","EV bays"];

export default function Home(){return <>
<section className="hero"><div className="hero-orbit orbit-a"/><div className="hero-orbit orbit-b"/><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow">AI-assisted parking guidance</span><h1 className="h1">Parking rules,<br/><span className="blue-text">made simple.</span></h1><p className="lead">Scan parking signs, road markings and other parking evidence. NaviParka helps explain whether you can park—and the conditions you need to know.</p><div className="actions"><Link href="/download" className="btn btn-primary btn-lg">Get NaviParka <ArrowRight size={17}/></Link><Link href="/how-it-works" className="btn btn-secondary btn-lg">See how it works</Link></div><div className="trust-strip"><span><CheckCircle2 size={15}/> Android first</span><span><ShieldCheck size={15}/> Safety-conscious AI</span><span><Navigation2 size={15}/> Built for UK parking</span></div></div><div className="hero-device"><PhoneMockup kind="scanner"/><div className="floating-proof proof-one"><ScanLine size={16}/><span><b>Evidence detected</b><small>Sign + road marking</small></span></div><div className="floating-proof proof-two"><CheckCircle2 size={16}/><span><b>Clear result</b><small>Conditions explained</small></span></div></div></div></section>

<section className="section section-tight"><div className="container"><div className="section-heading centered"><span className="eyebrow">The NaviParka flow</span><h2 className="h2">From confusing signs to a clear answer.</h2><p className="lead">One simple flow designed around the moment drivers actually need help.</p></div><div className="flow-grid"><div className="flow-card"><div className="flow-top"><span>01</span><Camera size={24}/></div><h3>Scan</h3><p>Point your camera at the parking evidence in front of you.</p></div><div className="flow-arrow">→</div><div className="flow-card"><div className="flow-top"><span>02</span><BrainCircuit size={24}/></div><h3>Understand</h3><p>NaviParka analyses signs, markings, restrictions and context.</p></div><div className="flow-arrow">→</div><div className="flow-card"><div className="flow-top"><span>03</span><CheckCircle2 size={24}/></div><h3>Decide</h3><p>Get a clear parking decision and the conditions behind it.</p></div></div></div></section>

<section className="section"><div className="container grid2 product-split"><div className="visual-panel"><PhoneMockup kind="scanner" label="MOCKUP-SCANNER"/></div><div className="product-copy"><span className="eyebrow">AI Parking Scanner</span><h2 className="h2">Scan what you see. NaviParka works out what matters.</h2><p className="lead">Photograph a parking sign, bay, kerb or road markings. You don't need to choose what you're scanning first—NaviParka analyses the available parking evidence automatically.</p><div className="pillrow">{evidence.map(x=><span className="pill" key={x}>{x}</span>)}</div><Link href="/parking-scanner" className="text-link roomy">Explore the scanner <ArrowRight size={15}/></Link></div></div></section>

<section className="section decision-section"><div className="container"><div className="section-heading"><span className="eyebrow">Clear parking decisions</span><h2 className="h2">A parking answer you can actually understand.</h2><p className="lead">The decision comes first. Conditions, payment details and reasoning follow.</p></div><div className="grid3 result-grid"><ResultCard type="good" title="You can park here"><div className="status-row"><span>Allowed until</span><b>6:00 PM</b></div><div className="status-row"><span>Maximum stay</span><b>2 hours</b></div></ResultCard><ResultCard type="warn" title="You can park here if…"><div className="status-row"><span>Condition</span><b>Actively charging</b></div><div className="status-row"><span>Bay</span><b>EV only</b></div></ResultCard><ResultCard type="bad" title="Don't park here"><div className="status-row"><span>Restriction</span><b>Permit holders</b></div><div className="status-row"><span>Applies</span><b>8 AM–6 PM</b></div></ResultCard></div></div></section>

<section className="section"><div className="container grid2 product-split reverse-mobile"><div className="product-copy"><span className="eyebrow">Your vehicle matters</span><h2 className="h2">Parking rules can depend on what you drive.</h2><p className="lead">NaviParka can use saved vehicle information when interpreting restrictions that depend on fuel type or vehicle eligibility.</p><div className="context-list"><div><BatteryCharging size={19}/><span><b>Electric vehicle bays</b><small>Understand charging conditions and eligibility.</small></span></div><div><Car size={19}/><span><b>Vehicle-aware guidance</b><small>Use saved vehicle context where it matters.</small></span></div></div><Link href="/vehicle-awareness" className="text-link roomy">See vehicle awareness <ArrowRight size={15}/></Link></div><div className="visual-panel"><PhoneMockup kind="vehicle" label="MOCKUP-EV-RESULT"/></div></div></section>

<section className="section map-section"><div className="container"><div className="map-heading"><div><span className="eyebrow">Parking Map</span><h2 className="h2">Find parking with more context.</h2></div><p className="lead">Explore nearby parking options, understand restrictions around you and surface a useful <b>Best verified option</b>.</p></div><MapMockup/></div></section>

<section className="section"><div className="container"><div className="utility-grid"><div className="utility-card payment-card"><div className="utility-copy"><span className="utility-icon"><ReceiptText size={21}/></span><span className="eyebrow">Payment assistance</span><h3>Know how to pay before walking away.</h3><p>Where payment information can be identified, NaviParka can surface the provider, location code and relevant instructions.</p></div><div className="payment-ui"><div className="payment-head"><CreditCard size={20}/><b>Payment required</b></div><div className="status-row"><span>Provider</span><b>Payment service</b></div><div className="status-row"><span>Location code</span><b>804231</b></div><button className="screen-action">Open payment service <ArrowRight size={14}/></button></div></div><div className="utility-stack"><div className="mini-feature"><History size={22}/><div><h3>Remember what you scanned.</h3><p>Review previous parking scans and restrictions when you need them.</p></div><div className="history-sample"><span>Above Bar Street <b className="good-text">Allowed</b></span><span>Bedford Place <b className="bad-text">Permit only</b></span></div></div><div className="mini-feature"><Clock3 size={22}/><div><h3>Keep track of your parking time.</h3><p>Keep useful timing information close when a parking decision includes a time restriction.</p></div><div className="timer-sample"><strong>01:42:16</strong><small>remaining · ends 18:00</small></div></div></div></div></div></section>

<section className="section"><div className="container"><div className="trust-band"><div className="trust-copy"><span className="eyebrow">Built for real-world decisions</span><h2 className="h2">Helpful AI.<br/>Clear limitations.</h2><p className="lead">NaviParka helps drivers understand available parking evidence. Physical signage, temporary restrictions and local conditions still matter.</p><Link href="/safety" className="btn btn-secondary">Read about safety <ArrowRight size={16}/></Link></div><div className="trust-cards">{[["Evidence-first",ScanLine,"Starts with the parking evidence you can actually see."],["Clear reasoning",CheckCircle2,"Important conditions are surfaced alongside the result."],["Context-aware",Car,"Vehicle and situation can change the correct interpretation."],["Driver responsibility",ShieldCheck,"Always check local signage before leaving your vehicle."]].map(([t,I,d]:any)=><div className="trust-card" key={t}><span><I size={20}/></span><b>{t}</b><p>{d}</p></div>)}</div></div></div></section>

<section className="section"><div className="container uk-section"><div><span className="eyebrow">Built for UK parking</span><h2 className="h2">Starting locally. Built with a wider UK vision.</h2><p className="lead">NaviParka is being developed around the complexity of UK parking rules, with early product focus in Southampton and room to grow across the UK.</p></div><div className="location-card"><div className="location-ring"><MapPinned size={34}/></div><div><span className="eyebrow">Early focus</span><h3>Southampton</h3><p>United Kingdom</p></div><div className="location-route"/></div></div></section>

<section className="section final-section"><div className="container"><div className="final-cta"><div className="final-copy"><span className="eyebrow">NaviParka for Android</span><h2 className="h2">Know before you<br/>walk away.</h2><p className="lead">Make parking restrictions easier to understand with NaviParka.</p><Link href="/download" className="btn btn-primary btn-lg">Get NaviParka <ArrowRight size={16}/></Link><small>AI-assisted guidance. Always check local signage and conditions.</small></div><div className="final-device"><PhoneMockup kind="result" label="MOCKUP-FINAL-APP"/></div></div></div></section>
</>}
