import Link from "next/link";
import { ArrowRight, Camera, Map, Car, Clock3, History, ShieldCheck, CreditCard, ScanLine, Navigation, BatteryCharging, CheckCircle2, AlertTriangle, XCircle, MapPin, Navigation2, Sparkles, ChevronRight } from "lucide-react";
import {MobileMenu} from "@/components/interactive";

export const routes=[
  ["/how-it-works","How it works"],["/features","Features"],["/parking-scanner","AI Parking Scanner"],["/parking-map","Parking Map"],["/vehicle-awareness","Vehicle Awareness"],["/safety","Safety"],["/download","Download"],["/support","Support"]
] as const;

export function Header(){return <header className="nav"><div className="container navin"><Link href="/" className="logo" aria-label="NaviParka home"><span className="logo-mark"><Navigation2 size={16}/></span><span>Navi<b>Parka</b></span></Link><nav className="navlinks"><Link href="/features">Product</Link><Link href="/how-it-works">How it works</Link><Link href="/safety">Safety</Link><Link href="/support">Support</Link></nav><Link className="btn btn-primary navcta" href="/download">Get NaviParka <ArrowRight size={16}/></Link><MobileMenu/></div></header>}

export function Footer(){return <footer className="footer"><div className="container"><div className="footergrid"><div><div className="logo"><span className="logo-mark"><Navigation2 size={16}/></span><span>Navi<b>Parka</b></span></div><p>Parking rules, made simple.<br/>AI-assisted parking guidance for UK drivers.</p><div className="footer-badge">Built for UK parking</div></div><div><h4>Product</h4><Link href="/how-it-works">How it works</Link><Link href="/parking-scanner">AI Scanner</Link><Link href="/parking-map">Parking Map</Link><Link href="/vehicle-awareness">Vehicle Awareness</Link></div><div><h4>Help</h4><Link href="/safety">Safety</Link><Link href="/support">Support</Link><Link href="/support/faq">FAQ</Link><Link href="/support/contact">Contact</Link></div><div><h4>Legal</h4><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><Link href="/cookies">Cookies</Link><Link href="/accessibility">Accessibility</Link><Link href="/delete-account">Delete account</Link></div></div><div className="footerbottom"><span>© 2026 NaviParka. All rights reserved.</span><span>Always check local signage and conditions before leaving your vehicle.</span></div></div></footer>}

export function PhoneMockup({kind="scanner",label}:{kind?:string,label?:string}){return <div className="device-stage"><div className="device-glow"/><div className="phone" aria-label={label ?? `App mockup placeholder: ${kind}`}><div className="speaker"/><div className="phone-screen"><div className="app-top"><span className="app-wordmark">NaviParka</span><span className="app-dot"/></div>{kind==="scanner"?<><div className="scanview"><div className="scan-corners"><i/><i/><i/><i/></div><div className="sign">P<br/><span>Mon–Sat</span><br/><b>8am–6pm</b><br/><span>2 hours</span><br/><small>No return 1 hour</small></div><div className="scan-chip"><Sparkles size={14}/> Analysing parking evidence</div></div><div className="screen-copy"><b>Scan parking evidence</b><p>Point your camera at a parking sign or road markings.</p></div><div className="camera-control"><Camera size={22}/></div></>:kind==="result"?<><div className="result-screen"><div className="result-icon good"><CheckCircle2 size={20}/></div><div className="result-kicker good-text">PARKING RESULT</div><h3>You can park here</h3><p>Allowed until 6:00 PM</p><div className="screen-detail"><span>Maximum stay</span><b>2 hours</b></div><div className="screen-detail"><span>Payment</span><b>Required</b></div><button className="screen-action">View full details <ChevronRight size={15}/></button></div></>:kind==="vehicle"?<><div className="result-screen"><div className="result-kicker">VEHICLE CONTEXT</div><h3>Electric vehicle bay</h3><p>Your saved vehicle is electric.</p><div className="vehicle-mini"><div className="vehicle-icon"><Car size={18}/></div><div><b>Your vehicle</b><span>Electric</span></div><BatteryCharging size={18}/></div><div className="eligibility"><CheckCircle2 size={18}/><div><b>Eligible</b><span>You may park while actively charging, subject to local conditions.</span></div></div></div></>:<><div className="placeholder-screen"><div className="eyebrow">NaviParka</div><h3>App screen placeholder</h3><p>Your real NaviParka screenshot will replace this area later.</p></div></>}</div></div>{label&&<div className="mockup-label">{label}</div>}</div>}

export function ResultCard({type,title,children}:{type:'good'|'warn'|'bad',title:string,children:React.ReactNode}){const Icon=type==='good'?CheckCircle2:type==='warn'?AlertTriangle:XCircle;return <div className={`card status-card ${type}`}><div className="status-accent"/><div className="status-top"><Icon size={17}/> {type==='good'?'ALLOWED':type==='warn'?'CONDITIONAL':'RESTRICTED'}</div><div className="status-title">{title}</div>{children}<div className="status-footer">View reasoning <ArrowRight size={14}/></div></div>}

export function MapMockup(){return <div className="card map"><div className="map-grid"/><div className="road one"/><div className="road two"/><div className="road three"/><div className="map-label city">SOUTHAMPTON</div><div className="map-label bedford">Bedford Place</div><div className="map-label civic">Civic Centre</div><div className="pin" style={{left:'19%',top:'25%'}}>P</div><div className="pin" style={{left:'70%',top:'18%'}}>P</div><div className="pin ev" style={{left:'61%',top:'65%'}}>⚡</div><div className="pin" style={{left:'34%',top:'57%'}}>P</div><div className="you" style={{left:'48%',top:'43%'}}><span/></div><div className="card best"><div className="best-top"><div className="eyebrow">Best verified option</div><span className="best-distance">4 min</span></div><h3 className="h3">Nearby parking option</h3><div className="best-meta"><span><MapPin size={14}/> Southampton city centre</span><span><ShieldCheck size={14}/> Restrictions reviewed</span></div><Link href="/parking-map" className="text-link">View option <ArrowRight size={15}/></Link></div></div>}

export const featureIcons={scanner:ScanLine,map:Map,vehicle:Car,payment:CreditCard,history:History,timer:Clock3,safety:ShieldCheck,charging:BatteryCharging,navigation:Navigation,camera:Camera};
export function PageHero({eyebrow,title,body,children}:{eyebrow:string,title:string,body:string,children?:React.ReactNode}){return <section className="pagehero"><div className="container"><span className="eyebrow">{eyebrow}</span><h1 className="h1">{title}</h1><p className="lead">{body}</p>{children}</div></section>}
